service: pixel

image: justinpaulson/pixel

servers:
  web:
    - 54.221.142.206
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

proxy:
  ssl: true
  host: pixel.justinpaulson.com

registry:
  server: 874101457773.dkr.ecr.us-east-1.amazonaws.com
  username: AWS
  password: <%= %x(aws --region=us-east-1 ecr get-login-password) %>

ssh:
  user: ubuntu

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "pixel_bot_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
  secrets:
    - RAILS_MASTER_KEY
